# Generated by Django 3.1.6 on 2021-02-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
