# Generated by Django 3.1.6 on 2021-02-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
