# Generated by Django 3.1.6 on 2021-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApplication', '0002_remove_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
